### ISSUE TITLE
CIF

### ISSUE THREAD

**Issue by sackboyro** [itrack/anaf#1]
Salut,
Este posibil sa se ia si CIF-ul pentru o societate?
Multumesc

**Comment by itrack** [comment]
Salut,
CIF este acelasi lucru cu CUI, pentru mai multe detalii poti sa te uiti aici:
https://ro.wikipedia.org/wiki/Cod_de_Identificare_Fiscal%C4%83

Seara faina!

**Comment by sackboyro** [comment]
scuzele mele, ma refeream lanr de ordine in registrul comertului ... JZZ/ ...

**Comment by itrack** [comment]
Din pacate vad ca API-ul ANAF nu ofera informatia asta darrr am gasit ceva pentru tine.
Listele cu toate firmele inregistrate in Romania, ele au si NR. Reg Comertului:
http://data.gov.ro/organization/onrc

Sper sa te ajute.
Bafta!

**Comment by itrack** [comment]
P.S. sunt actualizate odata la cateva luni

**Comment by sackboyro** [comment]
ok, iti multumesc.
