### ISSUE TITLE
cifs: protected

### ISSUE THREAD

**Issue by mosteanucatalin** [itrack/anaf#18]
object(Itrack\Anaf\Client)#10 (1) { ["cifs":protected]=> array(0) { } }
Fatal error: Uncaught Itrack\Anaf\Exceptions\ResponseFailed: Response status: 0

Problema am observat-o la inceputul anului acesta. La inceput au fost doar cateva situatii cand primeam eroarea, acum este permanenta. 

    $anaf = new \Itrack\Anaf\Client(); 
    var_dump($anaf);
    $anaf->addCif($cif);

**Comment by itrack** [comment]
Salut, cei de la ANAF au probleme cu serverele , exceptia este ResponseFailed, status 0 primesti in cazul timeout.
Ce as recomanda, ar fi sa reincerci verificarea odata la o perioada.

Voi implementa o exceptie in cazul timeout pentru a o urmari mai bine. Si un sistem de retry mai potent, exista ceva doar pentru cazul in care raspunsul nu este in format json.
