### ISSUE TITLE
API cazut

### ISSUE THREAD

**Issue by velicuicristian** [itrack/anaf#19]
Salutare,

Folosim scriptul si am folosit de ceva timp url-ul https://webservicesp.anaf.ro/PlatitorTvaRest/api/v8/ws/tva care este public la ANAF, insa sunt cateva zile de cand acesta este picat, raspunde numai cu 

The requested URL was rejected. Please consult with your administrator.

Your support ID is: 8096782510241224773

Aveti idee ce se intampla :-) ?

**Comment by alexban14** [comment]
Salutare,

Si eu patesc la fel. E posibil cum pentru aceasta librarie nu ai nevoie de token client id si client secret din partea ANAF-ului, acestia fi seseizat numarul mare de request-uri venite din parte unui singru toke si sa i fi revocat accesul?

**Comment by velicuicristian** [comment]
A fost ceva din sistemul lor, acum vad ca functioneaza corect. Mai am o curiozitate din ce sursa oare iau astia datele https://targetare.ro/lista-firme-nou-infiintate Le au aproape in timp real cu firme noi infiintate. :-D

> Salutare,
> 
> Si eu patesc la fel. E posibil cum pentru aceasta librarie nu ai nevoie de token client id si client secret din partea ANAF-ului, acestia sa fi seseizat numarul mare de request-uri venite din parte unui singru toke si sa i fi revocat accesul?

**Comment by itrack** [comment]
> Salutare,
> 
> Si eu patesc la fel. E posibil cum pentru aceasta librarie nu ai nevoie de token client id si client secret din partea ANAF-ului, acestia sa fi seseizat numarul mare de request-uri venite din parte unui singru toke si sa i fi revocat accesul?

Salut,
Este o problema cu API-ul ANAF. Am sesizat si eu weekendul tecut o situatie similara.
Probabil dupa ce au pus in functiune e-factura au ramas fara banda :))

Libraria nu are client id , token pentru ca pentru acest endpoint ANAF nu are autentificare:
Documentatia aici: https://webservicesp.anaf.ro/PlatitorTvaRest/api/v8/

Observ ca acum si-a revenit API-ul.



> A fost ceva din sistemul lor, acum vad ca functioneaza corect. Mai am o curiozitate din ce sursa oare iau astia datele https://targetare.ro/lista-firme-nou-infiintate Le au aproape in timp real cu firme noi infiintate. :-D
> 
> > Salutare,
> > Si eu patesc la fel. E posibil cum pentru aceasta librarie nu ai nevoie de token client id si client secret din partea ANAF-ului, acestia sa fi seseizat numarul mare de request-uri venite din parte unui singru toke si sa i fi revocat accesul?

Vezi pe https://data.gov.ro/, se actualizeaza odata la ~2 luni, ultima actualizare este din 07 ianuarie 2024
