### ISSUE TITLE
vendor... nu merge

### ISSUE THREAD

**Issue by codeguru1983** [itrack/anaf#2]
Salut, am incercat si pe windows si pe ubuntu composerul si nu merge imi zice ca nu gaseste repositorul, ai idee daca e totul in regula sau fac eu ceva aiurea?

multumesc!

**Comment by itrack** [comment]
Salut,
Ce versiune de PHP folosesti pe server?
Este posibil sa ai o versiune mai mica decat 5.5, poti verifica prin comanda "php -v"


Zi faina!

**Comment by itrack** [comment]
De asemenea poti verifica daca ai instalate extensiile de PHP din aceasta lista:
https://github.com/itrack/anaf#requirements
