### ISSUE TITLE
Fatal error: Class 'PHPUnit\Framework\TestCase' not found in C:\wamp64\www\anaf\tests\TestCase.php on line 9

### ISSUE THREAD

**Issue by codeguru1983** [itrack/anaf#3]
Salut,

In primul rand buna treaba, ma rog daca ar merge. Sa fiu si putin hater, nu inteleg de ce lucrurile trebuiesc facute asa complicate cand un simplu fisier era suficient... fisier demo cum sa tragi 1 firma, cum sa tragi 500 de firme. de ce-i nevoie de composer, de nervi si stres sa descarce n-spe lucruri doar ca intr-un final sa nu mearga... iti face iar subfoldere, iar trage continutul... mult prea complicat pentru un script de o pagina care se putea face mult mai usor ca toata lumea sa-l poata instala utiliza mai repede.

In fine, nici eu nu ma prea pricep. am reusit intr-un final sa-i dau de cap la composerul ala doar ca mi-a mai descarcat inca o data toate minunile de foldere + altele noi cu tot felul de chestii care oricum nu le inteleg rostul dar cand ma duc sa accesez direct TestCase.php imi da eraoarea asta cu clasa...aveti idee care-i treaba? sau ma rog, de ce nu se poate pune o chestie mult mai simplificata care sa poata fi utilizata direct dupa download in loc sa stai sa te mai cacai stanga dreapta inutil sa pierzi ore cand defapt ajungi tot la un download...

```
( ! ) Fatal error: Class 'PHPUnit\Framework\TestCase' not found in C:\wamp64\www\anaf\tests\TestCase.php on line 9
Call Stack
#	Time	Memory	Function	Location
1	0.0000	238296	{main}( )	...\TestCase.php:0

```

**Comment by itrack** [comment]
Salut,
O sa incerc sa clarific putin cele spuse de tine 😄 
Fisierele din proiect nu sunt inutile, adica daca esti la inceput da, pot parea inutile, daca ai experienta cu composerul, oop etc. le poti intelege utilitatea. In principiu o mare majoritate din proiectele PHP de pe Github sunt trecute prin composer pentru a le integra usor in proiectul tau (adica fara sa le copiezi manual, fara sa le dai tu include, rulezi doar "composer require .....numele librariei..." si merge).

Nu poti accesa manual TestCase.php, acesta este un test automat pentru PHPUnit, adica un tool pentru a testa automat ca functioneaza libraria. Poti vedea aici rezultatele testelor de la ultimul build:  https://github.com/itrack/anaf/runs/358737235

Sugestia mea ar fi sa faci asa:
- Executi intr-un director comanda: composer require itrack/anaf
- Descarci in acelasi director urmatorul fisier: https://github.com/itrack/anaf/blob/master/example.php
- Accesezi example.php si daca ai instalat un PHP mai mare sau egal cu versiunea 5.5 ar trebui sa mearga totul ok.

Zi faina
