### ISSUE TITLE
si din example.php

### ISSUE THREAD

**Issue by codeguru1983** [itrack/anaf#4]
asta da cand accesezi example.php direct din folderul anaf unde este si folderul vendor...

```

( ! ) Fatal error: Uncaught exception 'Itrack\Anaf\Exceptions\ResponseFailed' with message 'Response status: 0 \| Response body: ' in C:\wamp64\www\anaf\src\Client.php on line 119
--



1 | 0.0010 | 241888 | {main}( ) | ...\example.php:0
2 | 0.0290 | 585584 | Itrack\Anaf\Client->getResults( ) | ...\example.php:10
3 | 0.0290 | 585896 | Itrack\Anaf\Client->callApi( ) | ...\Client.php:62


```

**Comment by codeguru1983** [comment]
vad ca in client pe la linia 119 unde da eroarea din example.php se face referire si la link. vad ca linkul oficial este:

```
   const apiURL = '
------- pe site anaf:
	https://webservicesp.anaf.ro/AsynchWebService/api/v4/ws/tva

-------- original:
	https://webservicesp.anaf.ro/PlatitorTvaRest/api/v4/ws/tva';
```

**Comment by itrack** [comment]
Prima eroare inseamna "host no found", adica calculatorul tau nu se poate conecta la API-ul ANAF (nu ai conexiune la net, ai schimbat url-ul api-ului sau alte motive care tin de setarea PHP-ului de pe masina ta)
--------

In legatura cu al doilea comentariu, exista 2 API-uri, unul sincron altul asincron:

Asincron: https://static.anaf.ro/static/10/Anaf/Informatii_R/doc_WS_Async_V4.txt
Sincron: https://static.anaf.ro/static/10/Anaf/Informatii_R/doc_WS_V4.txt

Ambele sunt oficiale si au intr-un final acelasi raspuns, diferenta este ca pentru unul trebuie sa faci un call in api si pentru altul 2.
Implementarea url-ului Asincron ar putea fi justificata doar daca cel sincron ar raspunde foarte greu, dar nu este cazul.

In concluzie ambele url-uri sunt oficiale si functioneaza ok, cel sicron este cea mai buna varianta pentru un utilizator simplu.
