### ISSUE TITLE
daca se depasesc 10 caractere  - status 500 

### ISSUE THREAD

**Issue by stardand** [itrack/anaf#6]
<b>Fatal error</b>:  Uncaught Itrack\Anaf\Exceptions\ResponseFailed: Response status: 500 
<b> itrack/anaf/src/Client.php</b> on line <b>119</b>

**Comment by itrack** [comment]
Hello,
Nu exista CIF de 10 caractere, conform wiki avem maxim 9, https://ro.wikipedia.org/wiki/Cod_de_identificare_fiscal%C4%83
Dar pe viitor se poate face un validator.

**Comment by stardand** [comment]
Sigur, este doar o observatie, pentru ca alti utilizatori sa inteleaga de ce este important sa tratam exceptiile prin try -> catch
