### ISSUE TITLE
How do I know if the CUI is invalid in case of a company which existed in the past?

### ISSUE THREAD

**Issue by galkrisztina** [itrack/anaf#7]
Hi!
If I give an invalid CUI, then I can refer to the `denumire` and `adresa` fields's empty value to know in my logic that the CUI is invalid. But do you have some solution to find out if the CUI is invalid in case of a company which existed in the past, but it doesn't exists for the given date?
Thanks,
Krisztina

**Comment by itrack** [comment]
Hi!
I wouldn't know how to answer that question, one solution would be to download the databases from RegCom:

https://data.gov.ro/organization/onrc
